### ISSUE TITLE
Sets de Entrenamiento, Validación y Test

### ISSUE THREAD

**Issue by aeavalos** [ICT3115/Syllabus-2021-1#4]
Al ver el tema de los sets, nos surgió la siguiente duda, ¿la idea es mantener siempre la misma separación entrenamiento-test? En otras palabras, ¿una vez que empezamos a entrenar con un set de entrenamiento lo debemos guardar para luego entrenar todas las otras redes con el mismo o podemos entrenar las arquitecturas con distintos sets aleatorios del mismo tamaño?

**Comment by halobel** [comment]
Hola Andrés, se puede hacer de las dos maneras, pero por un tema de tiempo recomiendo la primera, ya que en la segunda, para no sesgar los modelos de manera distinta, es necesario entrenar cada uno múltiples veces con distintos sets aleatorios.
Al entrenar con una partición fija de training-test, igualmente sesgas los modelos, pero todos tienen el mismo sesgo en los datos, por lo que no hay problema en compararlos.

**Comment by aeavalos** [comment]
Perfecto, muchas gracias!
